### ISSUE TITLE
feature [Open the folder with the OS] do not avalible

### ISSUE THREAD

**Issue by duiliuliu** [xyhp915/logseq-assets-plus#7]
When I click the Folder button, no action is triggered, and I've noticed an error reported in the console:

Uncaught (in promise) Error: Not existed method #showItemInFolder
    at br.R (lsplugin.core.js:2:49378)
    at br.<anonymous> (lsplugin.core.js:2:93340)
    at a.emit (lsplugin.core.js:2:28521)
    at X.<anonymous> (lsplugin.core.js:2:88623)
    at lsplugin.core.js:2:53506
    at Array.forEach (<anonymous>)
    at X.listener (lsplugin.core.js:2:53491)

**Comment by duiliuliu** [comment]
Additionally, I would like to inquire:

- The `showItemInFolder` API is something I wish to utilize in my plugin **[LogseqFileManage](https://github.com/duiliuliu/logseq-plugin-files-manager)**. Is it possible to get official support for this API from Logseq?

- The `FileSystemDirectoryHandle` obtained from Logseq through `showDirectoryPicker` does not have the permission to delete files. However, I have many unnecessary attachments that I would like to delete through the plugin. Do you have any alternative suggestions for implementation?
